# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2026-03-12 18:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0006_invitation_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='invitee',
            field=models.OneToOneField(blank=True, help_text='The user who was invited after he accepts the invitation and registers himself. NULL for pending and expired invitations.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invited_with', to=settings.AUTH_USER_MODEL),
        ),
    ]
