# Generated by Django 5.0.14 on 2026-03-12 19:48

from django.db import migrations

from poleno.utils.migrations import RenameOrAddIndex


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0004_name_sanitization'),
    ]

    operations = [
        RenameOrAddIndex(
            model_name='attachment',
            new_name='attachments_generic_c72005_idx',
            old_fields=('generic_type', 'generic_id'),
        ),
    ]
