# Generated by Django 2.0.13 on 2026-03-12 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('obligees', '0014_auto_20260311_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalobligee',
            name='iczsj',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='City neighbourhood the obligee address is in.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='geounits.Neighbourhood'),
        ),
    ]
