# Generated by Django 3.0.14 on 2026-03-12 19:22

from django.db import migrations, models
import poleno.utils.forms


class Migration(migrations.Migration):

    dependencies = [
        ('obligees', '0015_auto_20260312_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalobligee',
            name='emails',
            field=models.CharField(blank=True, help_text='Comma separated list of e-mails. E.g. &#x27;John &lt;john@example.com&gt;, another@example.com, &quot;Smith, Jane&quot; &lt;jane.smith@example.com&gt;&#x27;. Empty the email address is unknown.', max_length=1024, validators=[poleno.utils.forms.validate_comma_separated_emails]),
        ),
        migrations.AlterField(
            model_name='obligee',
            name='emails',
            field=models.CharField(blank=True, help_text='Comma separated list of e-mails. E.g. &#x27;John &lt;john@example.com&gt;, another@example.com, &quot;Smith, Jane&quot; &lt;jane.smith@example.com&gt;&#x27;. Empty the email address is unknown.', max_length=1024, validators=[poleno.utils.forms.validate_comma_separated_emails]),
        ),
    ]
