# Generated by Django 5.0.14 on 2026-03-12 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obligees', '0016_auto_20260312_2022'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalobligee',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical obligee', 'verbose_name_plural': 'historical obligees'},
        ),
        migrations.AlterField(
            model_name='historicalobligee',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
    ]
