# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2026-03-12 18:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0005_address_name_encoding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='type',
            field=models.SmallIntegerField(choices=[(1, 'mail:Message:type:INBOUND'), (2, 'mail:Message:type:OUTBOUND')]),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='status',
            field=models.SmallIntegerField(choices=[(8, 'mail:Recipient:status:INBOUND'), (1, 'mail:Recipient:status:UNDEFINED'), (2, 'mail:Recipient:status:QUEUED'), (3, 'mail:Recipient:status:REJECTED'), (4, 'mail:Recipient:status:INVALID'), (5, 'mail:Recipient:status:SENT'), (6, 'mail:Recipient:status:DELIVERED'), (7, 'mail:Recipient:status:OPENED')], help_text='Delivery status for the message recipient. It must be "Inbound" for inbound mesages or one of the remaining statuses for outbound messages.'),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='type',
            field=models.SmallIntegerField(choices=[(1, 'mail:Recipient:type:TO'), (2, 'mail:Recipient:type:CC'), (3, 'mail:Recipient:type:BCC')], help_text='Recipient type: To, Cc, or Bcc.'),
        ),
    ]
