# Generated by Django 5.0.14 on 2026-03-12 19:48

from django.db import migrations

from poleno.utils.migrations import RenameOrAddIndex


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0006_auto_20260312_1958'),
    ]

    operations = [
        RenameOrAddIndex(
            model_name='message',
            new_name='mail_messag_process_cf5c71_idx',
            old_fields=('processed', 'id'),
        ),
        RenameOrAddIndex(
            model_name='message',
            new_name='mail_messag_created_422214_idx',
            old_fields=('created', 'id'),
        ),
    ]
