# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2026-03-12 18:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inforequests', '0026_auto_20260311_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='advanced_by',
            field=models.ForeignKey(blank=True, db_index=False, help_text='NULL for main branches. The advancement action the inforequest was advanced by for advanced branches. Every Inforequest must contain exactly one main branch.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advanced_to_set', to='inforequests.Action'),
        ),
        migrations.AlterField(
            model_name='inforequestdraft',
            name='obligee',
            field=models.ForeignKey(blank=True, help_text='The obligee the inforequest will be sent to, if the user has already set it.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='obligees.Obligee'),
        ),
    ]
