# Generated by Django 3.2.25 on 2026-03-12 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inforequests', '0027_auto_20260312_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inforequest',
            name='published',
            field=models.BooleanField(help_text='NULL if the inforequest will be published automatically. False if the inforequest will never be published automatically. True if the inforequest is published and everybody can see it. Non-published inforequests can be seen only by the user who created them.', null=True),
        ),
    ]
